# Generated by Django 5.1.1 on 2024-10-08 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_funcionario_cep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='telefone',
            field=models.CharField(blank=True, help_text='Coloque no seguinte formato: 00123456789', max_length=50),
        ),
    ]
