# Generated by Django 5.0.7 on 2024-09-02 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cargo',
            old_name='contratos',
            new_name='contrato',
        ),
        migrations.AlterField(
            model_name='contabancaria',
            name='funcionario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='api.funcionario', verbose_name='funcionario'),
        ),
    ]
