# Generated by Django 5.0.7 on 2024-09-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_contratos_cargo_contrato_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='nome',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
