# Generated by Django 5.0.7 on 2024-09-04 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_funcionario_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contabancaria',
            name='funcionario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='contaBancaria', to='api.funcionario', to_field='nome'),
        ),
    ]
