# Generated by Django 5.0.7 on 2024-09-06 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_contabancaria_funcionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='contrato',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='api.contrato'),
        ),
        migrations.AlterField(
            model_name='contabancaria',
            name='funcionario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='api.funcionario'),
        ),
        migrations.AlterField(
            model_name='duracao',
            name='contrato',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='api.contrato'),
        ),
        migrations.AlterField(
            model_name='empresa_terceiros',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.contrato'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='nome',
            field=models.CharField(max_length=50),
        ),
    ]
